import type { Metadata } from "next";
import "../globals.css";
import { Footer, Header } from "@/components/common";

export const metadata: Metadata = {
  title: "EPL News",
  // description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
