import "../globals.css";
import { Prompt } from "next/font/google";

const prompt = Prompt({
  subsets: ["latin"], // 한글 포함하고 싶으면 ['latin', 'latin-ext', 'korean']
  display: "swap", // 폰트 로딩 전략
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "INFOOTBALL",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className=''>
      <body className={prompt.className}>{children}</body>
    </html>
  );
}
